const $=s=>document.querySelector(s);
const screens={title:$('#titleScreen'),game:$('#gameScreen'),battle:$('#battleScreen'),inventory:$('#inventoryScreen'),chapter:$('#chapterScreen')};
const state={zone:'market',x:45,y:75,hp:55,maxHp:55,coins:0,items:[],flags:{yvette:false,gerard:false,marketLoot:false,marcel:false,streetLoot:false},enemyHp:0,enemyMax:0,guard:false};
function save(){localStorage.setItem('mamieSave',JSON.stringify(state))}
function load(){try{const s=JSON.parse(localStorage.getItem('mamieSave'));if(s)Object.assign(state,s)}catch{}}
function show(name){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[name].classList.add('active')}
function sync(){ $('#hpHud').textContent=state.hp;$('#coinHud').textContent=state.coins;$('#itemHud').textContent=state.items.length;renderZone();save()}
function say(who,text){$('#speaker').textContent=who;$('#line').textContent=text}
function obj(t){$('#objective').textContent=t}
function renderZone(){const w=$('#world'),m=$('#npcMarcel');w.classList.toggle('market',state.zone==='market');w.classList.toggle('street',state.zone==='street');m.classList.toggle('hidden',state.zone!=='street');$('#zoneLabel').textContent=state.zone==='market'?'CHAPITRE 1 — LE MARCHÉ':'CHAPITRE 2 — LA GRANDE RUE';if(state.zone==='market'){if(!state.flags.yvette)obj('Parler à Yvette');else if(!state.flags.gerard)obj('Trouver Gérard');else obj('Prendre la Grande Rue')}else{if(!state.flags.marcel)obj('Interroger Marcel au bistrot');else obj('Chercher un indice près de la mairie')}const h=$('#hero');h.style.left=state.x+'%';h.style.top=state.y+'%'}
function start(reset=false){if(reset)localStorage.removeItem('mamieSave');load();show('game');sync();say('Mamie','« Lucas ! Le goûter va refroidir ! »')}
$('#continueBtn').onclick=()=>start(false);$('#newBtn').onclick=()=>{Object.assign(state,{zone:'market',x:45,y:75,hp:55,maxHp:55,coins:0,items:[],flags:{yvette:false,gerard:false,marketLoot:false,marcel:false,streetLoot:false}});start(true)}
const near=(a,b,r=14)=>Math.hypot(state.x-a,state.y-b)<r;
function move(dx,dy){state.x=Math.max(3,Math.min(90,state.x+dx));state.y=Math.max(37,Math.min(83,state.y+dy));$('#hero').style.left=state.x+'%';$('#hero').style.top=state.y+'%';updatePrompt()}
function updatePrompt(){let t='';if(state.zone==='market'){if(near(14,59))t='Parler à Yvette';else if(near(78,58))t='Parler à Gérard';else if(near(49,57))t='Se reposer';else if(near(79,66))t='Fouiller';else if(state.flags.gerard&&near(92,50,18))t='Aller à la Grande Rue'}else{if(near(18,58))t='Parler à Marcel';else if(near(69,55))t='Se reposer';else if(near(82,70))t='Fouiller près de la mairie'}$('#prompt').textContent=t;$('#prompt').classList.toggle('show',!!t)}
$('#actionBtn').onclick=()=>{if(state.zone==='market'){if(near(14,59)){state.flags.yvette=true;say('Yvette','« Lucas ? Ça fait longtemps que je ne l’ai pas vu ici… Gérard voulait te parler. »');sync();return}if(near(78,58)){if(!state.flags.yvette){say('Gérard','« Va voir Yvette d’abord, Ginette. »');return}if(!state.flags.gerard){startBattle('gerard');return}say('Gérard','« La Grande Rue est libre. Et… Ginette, Lucas a grandi. »');return}if(near(49,57)){state.hp=state.maxHp;say('Mamie','« Mes genoux me remercient. »');sync();return}if(near(79,66)&&!state.flags.marketLoot){state.flags.marketLoot=true;state.coins+=20;state.items.push({name:'Bonbon à la menthe',desc:'Rend 12 PV en combat.'});say('Mamie','« Ce chat cache mieux son argent que la banque. »');sync();return}if(state.flags.gerard&&near(92,50,18)){state.zone='street';state.x=12;state.y=62;showChapter('CHAPITRE 2 — LA GRANDE RUE','Bistrot, mairie et parc. Quelqu’un a peut-être vu Lucas.');sync();return}}else{if(near(18,58)){state.flags.marcel=true;say('Marcel','« Lucas ? Le gamin ? Ginette… il avait déjà une voiture quand mon bistrot avait encore des rideaux orange. »');sync();return}if(near(69,55)){state.hp=state.maxHp;say('Mamie','« Un petit banc et ça repart. »');sync();return}if(near(82,70)&&!state.flags.streetLoot){state.flags.streetLoot=true;state.items.push({name:'Photo froissée',desc:'Lucas adulte devant une maison. Mamie refuse d’y croire.'});state.coins+=35;say('Mamie','« Ce monsieur ressemble à Lucas… drôle de coïncidence. »');sync();return}}say('Mamie','« Rien ici… Lucas ! »')}
function startBattle(type){state.enemyHp=60;state.enemyMax=60;state.guard=false;$('#enemyName').textContent='Gérard';$('#battleName').textContent='GÉRARD LE POISSONNIER';$('#enemySprite').src='assets/gerard.svg';$('#battleLog').textContent='« Pas par là, Ginette ! »';updateBattle();show('battle')}
function updateBattle(){$('#mamieHpBar').style.width=(state.hp/state.maxHp*100)+'%';$('#enemyHpBar').style.width=(state.enemyHp/state.enemyMax*100)+'%'}
function bump(el){el.classList.remove('hurt');void el.offsetWidth;el.classList.add('hurt')}
function enemyTurn(){const dmg=state.guard?0:8;state.guard=false;state.hp=Math.max(0,state.hp-dmg);updateBattle();bump($('.fighter:not(.enemy) img'));$('#battleLog').textContent=dmg?'Gérard balance un bar : -8 PV !':'Le cardigan bloque le poisson !';if(state.hp<=0)setTimeout(()=>{state.hp=state.maxHp;state.x=49;state.y=57;show('game');say('Mamie','« J’ai fait un petit malaise. Rien de grave. »');sync()},650)}
document.querySelectorAll('[data-move]').forEach(btn=>btn.onclick=()=>{const m=btn.dataset.move;if(m==='guard'){state.guard=true;$('#battleLog').textContent='Mamie remonte son cardigan.';setTimeout(enemyTurn,380);return}const dmg=m==='hot'?14:m==='bag'?10:8;state.enemyHp=Math.max(0,state.enemyHp-dmg);updateBattle();bump($('.enemy img'));$('#battleLog').textContent=btn.childNodes[0].textContent.trim()+' : '+dmg+' dégâts !';if(state.enemyHp<=0){state.flags.gerard=true;state.coins+=80;state.items.push({name:'Clé de la Grande Rue',desc:'Ouvre le passage derrière la poissonnerie.'});setTimeout(()=>{show('game');say('Gérard','« Ginette… Lucas n’est plus vraiment un petit… »');sync()},520)}else setTimeout(enemyTurn,380)})
$('#bagBtn').onclick=()=>{renderBag();screens.inventory.classList.add('active')};$('#closeBag').onclick=()=>screens.inventory.classList.remove('active');
function renderBag(){const box=$('#inventoryList');box.innerHTML=state.items.length?state.items.map(i=>'<div class="invItem"><div><b>'+i.name+'</b><br><small>'+i.desc+'</small></div></div>').join(''):'<p>Le sac est vide.</p>'}
function showChapter(t,p){$('#chapterTitle').textContent=t;$('#chapterText').textContent=p;screens.chapter.classList.add('active')}$('#chapterContinue').onclick=()=>screens.chapter.classList.remove('active');
let active=false,sx=0,sy=0;const stick=$('#stick'),nub=$('#nub');stick.addEventListener('pointerdown',e=>{active=true;stick.setPointerCapture(e.pointerId);sx=e.clientX;sy=e.clientY});stick.addEventListener('pointermove',e=>{if(!active)return;const dx=Math.max(-34,Math.min(34,e.clientX-sx)),dy=Math.max(-34,Math.min(34,e.clientY-sy));nub.style.transform='translate('+dx+'px,'+dy+'px)';if(Math.abs(dx)>8||Math.abs(dy)>8)move(dx/64,dy/64)});stick.addEventListener('pointerup',()=>{active=false;nub.style.transform='none'});